### ISSUE TITLE
Provide a sans-serif version

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/unstyle#22]
Inspired on this very nice clean style in http://hpurmann.com. It essentially consists in:

```css
body {
    font-family: sans-serif;
    font-weight: 300;
}
```
