### ISSUE TITLE
extra: readability mode

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/unstyle#28]
Something similar to this might be interesting to try out (click for full-size image):

<img width="1427" alt="screen shot 2017-04-16 at 18 12 00" src="https://cloud.githubusercontent.com/assets/478237/25072818/53b1bf0a-22d0-11e7-92d4-ddd1dfb5ee82.png">

**Comment by waldyrious** [comment]
quick & dirty:

```css
html {
  background: grey;
}

body {
  background: white;
  max-width: 40em;
  padding: 1em 5em;
  margin: 10px auto;
  border-radius: 2px;
  text-align: justify;
}
```
