### ISSUE TITLE
Investigate mini.css's table rules

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/unstyle#31]
and whether there's something we'd want to adopt/adapt.

https://chalarangelo.github.io/mini.css/table.html

**Comment by waldyrious** [comment]
Another table enhancement, which could be an interesting addition to this baseline style, is highlighting the current (hovered) row. This seems similar to the behavior implemented for links (they get underlined on hover).

Two possible ways to do this:

```css
tr:hover:after { content:"◂"; font-weight: normal; color: #ccc; margin-left:.3em; position: absolute; }
tr:hover, tr:hover th{ background: AliceBlue; }
```
